services:
  - type: web
    name: spur-compute-credits
    env: docker
    repo: https://github.com/spurnoc/spuric-compute-page
    branch: main
    plan: free
    envVars:
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
      - key: CF_ACCOUNT
        sync: false
      - key: CF_DB
        sync: false
      - key: CF_TOKEN
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: FOMO_PASSWORD
        sync: false
      - key: BASE_URL
        sync: false
